apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx          # must match the label on your pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: loadbalancer     # internal access only